# These categories will be applied to all DAGs in the repo.
categories:
  - AI + Machine Learning
  - Compute
  - Model Registry
  - ETL/ELT
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/feature-eng.py
  - path: dags/monitor-features.py
  - path: dags/retrain.py
  - path: dags/predict.py
  - path: dags/generate-true-values.py
